config/routes.rb
IndividulProject::Application.routes.draw do
  resources :system_admins

  resources :physicians

  resources :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :date, :name, :reason
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  attr_accessible :code, :name, :notes
end

app/models/system_admin.rb
class SystemAdmin < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @physicians }
    end
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
    @physician = Physician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @physician }
    end
  end

  # GET /physicians/new
  # GET /physicians/new.json
  def new
    @physician = Physician.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @physician }
    end
  end

  # GET /physicians/1/edit
  def edit
    @physician = Physician.find(params[:id])
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(params[:physician])

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render json: @physician, status: :created, location: @physician }
      else
        format.html { render action: "new" }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /physicians/1
  # PUT /physicians/1.json
  def update
    @physician = Physician.find(params[:id])

    respond_to do |format|
      if @physician.update_attributes(params[:physician])
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician = Physician.find(params[:id])
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/system_admins_controller.rb
class SystemAdminsController < ApplicationController
  # GET /system_admins
  # GET /system_admins.json
  def index
    @system_admins = SystemAdmin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @system_admins }
    end
  end

  # GET /system_admins/1
  # GET /system_admins/1.json
  def show
    @system_admin = SystemAdmin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @system_admin }
    end
  end

  # GET /system_admins/new
  # GET /system_admins/new.json
  def new
    @system_admin = SystemAdmin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @system_admin }
    end
  end

  # GET /system_admins/1/edit
  def edit
    @system_admin = SystemAdmin.find(params[:id])
  end

  # POST /system_admins
  # POST /system_admins.json
  def create
    @system_admin = SystemAdmin.new(params[:system_admin])

    respond_to do |format|
      if @system_admin.save
        format.html { redirect_to @system_admin, notice: 'System admin was successfully created.' }
        format.json { render json: @system_admin, status: :created, location: @system_admin }
      else
        format.html { render action: "new" }
        format.json { render json: @system_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /system_admins/1
  # PUT /system_admins/1.json
  def update
    @system_admin = SystemAdmin.find(params[:id])

    respond_to do |format|
      if @system_admin.update_attributes(params[:system_admin])
        format.html { redirect_to @system_admin, notice: 'System admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @system_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_admins/1
  # DELETE /system_admins/1.json
  def destroy
    @system_admin = SystemAdmin.find(params[:id])
    @system_admin.destroy

    respond_to do |format|
      format.html { redirect_to system_admins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/system_admins_helper.rb
module SystemAdminsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndividulProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Reason</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.name %></td>
    <td><%= patient.date %></td>
    <td><%= patient.reason %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @patient.name %>
</p>

<p>
  <b>Date:</b>
  <%= @patient.date %>
</p>

<p>
  <b>Reason:</b>
  <%= @patient.reason %>
</p>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h1>Listing physicians</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @physicians.each do |physician| %>
  <tr>
    <td><%= physician.name %></td>
    <td><%= physician.notes %></td>
    <td><%= physician.code %></td>
    <td><%= link_to 'Show', physician %></td>
    <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
    <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @physician.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @physician.notes %>
</p>

<p>
  <b>Code:</b>
  <%= @physician.code %>
</p>


<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>

app/views/system_admins/_form.html.erb
<%= form_for(@system_admin) do |f| %>
  <% if @system_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system_admin.errors.count, "error") %> prohibited this system_admin from being saved:</h2>

      <ul>
      <% @system_admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/system_admins/edit.html.erb
<h1>Editing system_admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @system_admin %> |
<%= link_to 'Back', system_admins_path %>

app/views/system_admins/index.html.erb
<h1>Listing system_admins</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @system_admins.each do |system_admin| %>
  <tr>
    <td><%= system_admin.name %></td>
    <td><%= link_to 'Show', system_admin %></td>
    <td><%= link_to 'Edit', edit_system_admin_path(system_admin) %></td>
    <td><%= link_to 'Destroy', system_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New System admin', new_system_admin_path %>

app/views/system_admins/new.html.erb
<h1>New system_admin</h1>

<%= render 'form' %>

<%= link_to 'Back', system_admins_path %>

app/views/system_admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @system_admin.name %>
</p>


<%= link_to 'Edit', edit_system_admin_path(@system_admin) %> |
<%= link_to 'Back', system_admins_path %>